### ISSUE TITLE
Two instances of set cookie on a new nerves project is confusing.

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_init_gadget#22]
```elixir
environment :dev do
  set cookie: :"E[vw}Jle^A4!!;jP58g58!TI[2,HV[|h=@!9G_BKndcXW~E1C`3qYcGxVCvpMt@="
end
```
There is two environment's in the release plugin config that look like that. This is _not_ the correct cookie. the Readme says to use the one in `vm.args` but if you ignore that, it is a little confusing.

**Comment by fhunleth** [comment]
I don't think there's anything that `nerves_init_gadget` can do to fix this. I agree that it's confusing which is why it's in the docs here. 

@mobileoverlord Is there anything that we can do in `nerves`? I think this issue should be moved over there.
