### ISSUE TITLE
Enable console access via ssh by default

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_init_gadget#28]
In #14, we reached the conclusion that ssh console access should be disabled by default. Now that it's so easy to add an ssh console, I'm finding that I want it enabled by default. Based on a couple slack questions, it seems like this would help others as well.

Anyone mind if we reverse the logic and have it come up on port 22 by default?

**Comment by ConnorRigby** [comment]
:+1:  from me.
