### ISSUE TITLE
The iex.exs file does not load over ssh

### ISSUE THREAD

**Issue by mattludwigs** [nerves-project/nerves_init_gadget#29]
It appears when I use ssh the `/etc/iex.exs` does not get loaded.

**Comment by fhunleth** [comment]
Confirmed. It works fine over serial, but not over ssh.

**Comment by mobileoverlord** [comment]
This issue is something that needs to be tackled in elixir. I've started looking into this, but have not had any success for evaluating the iex.exs file that was loaded on the console session on any of the remote sessions yet.

**Comment by fhunleth** [comment]
Fixed in https://github.com/nerves-project/nerves_init_gadget/commit/644a069b8dcb6db430a744cb1fe27ad1f2033753.
