### ISSUE TITLE
Can't discover device

### ISSUE THREAD

**Issue by fazibear** [nerves-project/nerves_init_gadget#61]
I've configured mDNS correctly. IP resolving works correctly, I can ping it via hostname, ssh to it. Because I'm using hostnames generated with mac address it will be nice I could discover them. 
Tried avahi discovery tool and Mdns.Client.query() with no luck.
Can I archive that without disabling mdns in init_gadget and manually starting id with a custom configuration?

**Comment by fhunleth** [comment]
The mDNS library needs some work and discovery would be at the top of my list. I don't think the original author has time anymore, so it would be great if someone could update it and take over maintenance.

**Comment by ConnorRigby** [comment]
I don't think init_gadget is intened to help discover a device. You might check out the [mdns](https://github.com/rosetta-home/mdns) lib for this.

**Comment by fazibear** [comment]
I've done a little research and:

```
Mdns.Server.add_service(%Mdns.Server.Service{domain: "_http._tcp.local",data: "SOMENAME._http._tcp.local",ttl: 4500,type: :ptr})
``` 
This service will make my device discoverable as "Web Site" by typing `avahi-browse -at`

To find device with `Mdns.Client.query()` I need to add another service:
```
Mdns.Server.add_service(%Mdns.Server.Service{domain: "_services._dns-sd._udp.local",data: "SOMENAME._services._dns-sd._udp.local",ttl: 4500,type: :ptr})
```

I'm still not sure what services should be added, but it should be added/changed in this repo.

**Comment by fhunleth** [comment]
Those are good finds! I think that advertising an `ssh` service would be appropriate for this repo.

**Comment by fazibear** [comment]
Sure, but `_ssh._tcp.local` won't work. Will figure it out and change it into PR
