### ISSUE TITLE
mDNS/linklocal fails the first time and sometimes permanently on OSX

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_init_gadget#8]
This may not be mDNS's or link local's fault, but they get blamed. The symptom is that after a reboot, you can't connect to or ping `nerves.local`. Sometimes it fixes itself. Linux works fine.

Here's what's happening:
1. The first set of packets from a laptop that go over the USB virtual Ethernet interface have their source IP address set to the IP address of another network interface.
2. The device receives them, tries to respond to the source, but it's pointless since the IP address is on a totally different network.
3. The laptop times out.

There are a few workarounds:
1. Disconnect the other network interface. When the USB virtual Ethernet interface is the only one, everything is fine.
2. Retry. It seems like OSX fixes itself after the first try or after a minute.
3. Have the program making the request bind to the USB virtual Ethernet interface

The root cause is unknown.

**Comment by adkron** [comment]
Is this an OSX only issue only, or is anyone running a BSD system that can verify it doesn't have the same issue?

**Comment by fhunleth** [comment]
My guess is that it's not a generic BSD issue, but I doubt that we have any non-OSX BSD users to verify it. The reason is that I haven't received a FreeBSD, etc. bug report on any of our constituent projects in a really long time. My experience has been that I inevitably break something on one of those BSDs. Sometimes it's a GNU-ism that works on OSX and sometimes it's a low level thing with `fwup`. It's pretty easy to do when you don't test on a BSD and as of last time I checked, there wasn't a FreeBSD CI system.

**Comment by fhunleth** [comment]
Updates: 

I investigated whether the Nerves IPv4 link-local implementation had anything to do with this bug. (See https://github.com/nerves-project/nerves_network/issues/42). I hard coded the ARP requests to probe whether the address was in use and then the gratuitous ARPs to announce the selected address. Unfortunately, this didn't change the behavior on my Mac.

I also investigated whether there was an analog in IPv4 for specifying address scope like the IPv6 scope or zone ID. This is the part after the percent sign in IPv6 for link-local addresses. I.e. the `eth0` part in `fe80::aabb.ccdd%eth0`. I didn't find anything. It seems like all programs need to be told the link's interface via a commandline parameter.

**Comment by jjcarstens** [comment]
@fhunleth Is there a workaround or way to fix this? I currently have a device that is just `wlan0` network setup and have suddenly lost the ability to get to it via `nerves.local` (although IP address still works fine).

At first it would just last a few minutes. Now I'm a week in and still can't see `nerves.local` on my network from MacOS. Although not sure if that is network setup or my configuration...

**Comment by fhunleth** [comment]
@jjcarstens Since you can ping the device, I assume that it's using DHCP to get an address and not link local. This particular issue deals with link local addressing. If you have any uncertainty, check your `config.exs` that both `nerves_init_gadget` and `nerves_network` are being told to use DHCP or post here. 

My second guess is that multicast is being filtered on your wireless LAN. Some access points do this, but they're usually corporate ones. To see if that's the problem, could you try running Wireshark on your Mac and look for mDNS requests and responses? If you can log into your Nerves device, you can also run `RingLogger.attach`. The mDNS client that we use is pretty noisy, so you should see the requests there as well.

**Comment by jjcarstens** [comment]
dang. 0/2 now on where I think my question should go 😞

I don't want to highjack this issue for something different, so I created this forum question and ported over your response. It will probably end up being very specific to my setup, but might help others later on (you never know)

https://elixirforum.com/t/cant-see-nerves-local-on-network-anymore/15786

**Comment by fhunleth** [comment]
Closing since it's now possible to run a mini DHCP server in v0.5.0 and avoid link-local. Add `address_method: :dhcpd` to your `nerves_init_gadget` configuration.
